version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGODB_INITDB_ROOT_USERNAME: foobar
      MONGODB_INITDB_ROOT_PASSWORD: foobarbaz
  
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_SETTINGS: config.DockerConfig
      FLASK_APP: app/main.py
      FLASK_DEBUG: 1
      MONGO_URI: "mongodb://mongo:27017/todos"
    links:
      - "mongo:mongo"
